"""Generating a random number and asking user to guess it, keeping track of the number of guesses it takes."""

__author__ = "730486310"

import random
points: int 
player: str
list_of_guesses: list[int] = []
EMOJI: str = "\U0001F389"


def main() -> None:
    """Allows the user to pick where they want to proceed in the program."""
    greet()
    global points
    points = 0
    experience: str = input(f"Hello {player}! In order to proceed, you must choose 1 of 3 options. To exit the game, type 'exit'. If you want to play, type 'play'. If you want to see a list of all your guesses at the end of the game, type 'guesses' when you are asked. ")
    while experience != "exit" and experience != "play":
        experience = input("Error, please try again: ")
    if experience == "exit":
        print(f"Thanks for playing! You guessed {points} times.")
    if experience == "play":
        play()
        guesses(points)
    experience = input("If you wish to see a list of all your guesses, type 'guesses'. If not, type 'leave'. ")
    while experience != "guesses" and experience != "leave":
        experience = input("Error, please try again: ")
    if experience == "guesses":
        print(f"Here is the list of guesses: {list_of_guesses}")
    if experience == "leave":
        print(f"Thanks for playing, {player}! Have a great day!")
    

def greet() -> None:
    """Greets the player to the game."""
    global player
    player = input("Welcome! In this game, you will have to guess a random number generated by me! You will be given a range of values to guess from, and I will keep track of how many guesses it takes you. What is your name? ")
    print(f"Good luck, {player}!")


def play() -> int:
    """The actual number guessing game."""
    i: int = 0
    num: int = random.randint(1, 20)
    guess: int = int(input(f"Hello, {player}. Guess a number between 1 and 20: "))
    while guess != num and i <= 21:
        list_of_guesses.append(guess)
        if guess < num:
            guess = int(input("Guess was too small. Try again: "))
        else:
            guess = int(input("Guess was too high. Try again: "))
        i += 1
    if guess == num:
        print(f"Congratulations! You guessed the correct number {EMOJI}")
        list_of_guesses.append(guess)
    global points
    points = i
    return num


def guesses(x: int) -> int:
    """Shows the player how many guesses it took them to guess the correct number."""
    global player
    if x == 0:
        print(f"Good afternoon {player}! You guessed the correct number in 1 try!")
    if x == 1:
        print(f"Good afternoon {player}! You guessed {x + 1} times!")
    if x != 0 and x != 1:
        print(f"Good afternoon {player}! You guessed the correct number in {x + 1} guesses!")
    return x


if __name__ == "__main__":
    main()